#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
COMPOSE_FILE="docker/docker-compose.yml"

HOST_UID="$(id -u)"
HOST_GID="$(id -g)"

if [ "${HOST_UID}" -eq 0 ]; then
    echo "error: run this as your normal user, not root" >&2
    exit 1
fi

cat > "${ENV_FILE}" <<ENVEOF
# Generated by docker/host_setup.sh. Do not commit.
HOST_UID=${HOST_UID}
HOST_GID=${HOST_GID}
ENVEOF
echo "wrote ${ENV_FILE} (HOST_UID=${HOST_UID}, HOST_GID=${HOST_GID})"

# Basic host checks. Warnings only, nothing is installed or changed.
if ! command -v docker >/dev/null 2>&1; then
    echo "warning: docker not found in PATH" >&2
elif ! docker compose version >/dev/null 2>&1; then
    echo "warning: docker compose plugin not available" >&2
elif ! docker info --format '{{json .Runtimes}}' 2>/dev/null | grep -q nvidia; then
    echo "warning: nvidia container runtime not registered, install nvidia-container-toolkit" >&2
fi

if ! command -v nvidia-smi >/dev/null 2>&1; then
    echo "warning: nvidia-smi not found, GPU driver may be missing" >&2
fi

cat <<MSG

Next steps (from the repo root):
  docker compose -f ${COMPOSE_FILE} build
  docker compose -f ${COMPOSE_FILE} up -d phonetic-candidate-dev
  docker compose -f ${COMPOSE_FILE} exec phonetic-candidate-dev bash

Re-run this script and rebuild if your UID or GID changes.
MSG
